GAIN_EXP:
  #setting số lượng level nhận vào khi giết mob
  VANILLA_MOB:
    ZOMBIE: 0.1
    SHEEP: 0.1
    CHICKEN: 0.5
  #setting số lượng level nhận vào khi giết mob mm
  MYTHIC_MOB:
    SkeletalKnight: 50.5
    Tên mob 2: 0.5
  #setting số lượng level nhận vào khi mine & farm
  BREAK:
    DIAMOND_ORE: 1.0
    GOLD_ORE: 1.0
    PUMPKIN: 1.0
    MELON_BLOCK: 1.0
#giới hạn cần để lên của từng level
SETTINGS:
  MAX_LEVEL: 100
  LEVEL_SCALE: 10*{level}
  #không viết có nghĩa là giữ nguyên limit này ở 3 và 4
  LEVEL_SPECIFIC:
    '2': 20
    '5': 50
  #Thực hiện command mỗi lần lên lv
  LEVEL_UP_COMMAND:
    - 'token give %player% 100'
  #Thực hiện command khi lên các mốc level xác định
  LEVEL_UP_COMMAND_SPECIFIC:
    '2':
      - 'msg %player% chúc mừng bạn đã lên cấp 2'
      - 'eco give %player% 10'
  PAPI:
    #%playerlevel_level%
    LEVEL: 'level'
    #%playerlevel_levelpoints%
    LEVEL_POINTS: 'levelpoints'
    #%playerlevel_levellimit%
    LEVEL_LIMIT: 'levellimit'
#Hiển thị format level tương ứng với perm tương ứng (khi player chat)
CHAT_FORMAT:
  PREFIXES:
    HE_HOA:
      PERM: 'he.hoa.perm'
      FORMAT: '§4Hoa {level} §7{player} >>'
    HE_THUY:
      PERM: 'he.thuy.perm'
      FORMAT: '§bThuy {level} §7{player} >>'
MESSAGES:
  #Prefix khi gửi thông báo
  PREFIX: '§c§l[PlayerLevel]'
  LEVEL_UP: '§cLevel up %old_level% -> %new_level%'
  GAIN_EXP: 'Bạn đã nhận được %amount% exp'
  RELOADED: 'Đã reload lại file'