#Prefix khi gửi thông báo
GAIN_EXP:
  #setting số lượng level nhận vào khi giết mob
  VANILLA_MOB:
    ZOMBIE: 0.1
    SHEEP: 0.1
  #setting số lượng level nhận vào khi giết mob mm
  MYTHICMOBS:
    Tên mob 1: 0.5
    Tên mob 2: 0.5
  #setting số lượng level nhận vào khi farm nông sản
  FARM:
    pumking: 1
    melon: 1
  #setting số lượng level nhận vào khi mine
  BREAK:
    DIAMOND_ORE: 1
    GOLD_ORE: 1
    PUMPKING: 1
    MELON: 1
#giới hạn cần để lên của từng level
SETTINGS:
  MAX_LEVEL: 50
  LEVEL_SCALE: 10*{level}
  #không viết có nghĩa là giữ nguyên limit này ở 3 và 4
  LEVEL_SPECIFIC:
    '2': 20
    '5': 50
  #mỗi lần lên 1 mốc lv được xác định sẽ thực hiện command
  LEVEL_UP_COMMAND:
    2:
      - 'msg {player} chúc mừng bạn đã lên cấp 2'
      - 'eco give {player} 10'
#Hiển thị format level tương ứng với perm tương ứng (khi player chat)
CHAT_FORMAT:
  PREFIXES:
    HE_HOA:
      PERM: 'he.hoa.perm'
      FORMAT: '§4Hoa {level} '
    HE_THUY:
      PERM: 'he.thuy.perm'
      FORMAT: '§bThuy {level} '
  PLACEHOLDERS:
    LEVEL: '{level} '
    LEVEL_POINTS: '{levelpoints}'
    LEVEL_LIMIT: '{levellimit}'
MESSAGE:
  PREFIX: '§c§l[PlayerLevel]'
  No-perm: '§cBạn không có quyền dung lệnh này'
  Reload-success: 'Đã reload lại file'
  Commands:
    - 'playerlevel set {player} {level}'
    - 'playerlevel give {player} {levelpoints}'